#ifndef ROBOT_DATABASE_GLOBAL_H
#define ROBOT_DATABASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROBOT_DATABASE_LIBRARY)
#  define ROBOT_DATABASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ROBOT_DATABASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ROBOT_DATABASE_GLOBAL_H
